### ISSUE TITLE
rules/klayout/drc/gf180mcu.drc: 3 separate runs of offgrid,beol,feol to cover all rules without duplicates; don't connect if just offgrid

### ISSUE THREAD

**Issue by sto6** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#10]
## Expected Behavior
No duplicates rules executed when run separate processes, each for just: beol, feol, offgrid, on same GDS. Want those 3 to "cover" all the rules, but without significant overlaps.
No connect statements should run when running just offgrid (despite conn_drc=true).
## Actual Behavior
About 200+ rules are unconditional, so separate runs beol,feol,offgrid repeat those 3x (wasting cpu & mem).
(For now in my local copy of rules, to avoid repeating these, I simply make them conditional to run only in BEOL, yet some are feol.)
This block is between these comments:
```
#---------------------MCELL----------------------
...
#-----------------GEOMETRY RULES-----------------
```
When running just offgrid but with conn_drc=true, connect statements are run (wasted).
Other duplicates, these six lines are each done twice:
```
ind_mk         = polygons(151, 5 )
ind_mk_count                   = ind_mk.count()
poly_count                     = poly_count + ind_mk_count
...
logger.info("Executing rule ind_mk_OFFGRID")
ind_mk.ongrid(0.005).output("ind_mk_OFFGRID", "OFFGRID : OFFGRID vertex on ind_mk")
ind_mk.with_angle(0 .. 45).output("ind_mk_angle", "ACUTE : non 45 degree angle ind_mk")
```
## Specifications
git@github.com:efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr.git
8cbf289 2022-12-01T00:12:24-08:00 (HEAD -> main, origin/main, origin/HEAD) Update run_drc_parallel.py

**Comment by atorkmabrains** [comment]
@sto6 This was fixed in the new release, please check and confirm if it's still there.
