### ISSUE TITLE
rules/klayout/drc/gf180mcu.drc: option processing, cannot turn off FEOL, BEOL. Both always run.

### ISSUE THREAD

**Issue by sto6** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#12]
## Expected Behavior
Should be: in absence of klayout cmd-line args: -rd feol=true, or case-variant the FEOL section does not run. Same for BEOL.
## Actual Behavior
FEOL, BEOL sections always run, regardless of args like -rd feol=false.

Code uses 'if FEOL ...' but assigns these flag-vars with strings, either keeping incoming $feol value ("false") or assigning literal "true". But a string value "false" is not interpreted by ruby as false. Only handling of $offgrid is correct. The $feol, $beol regardless of user-given value become effective true FEOL, BEOL, so there's no way to turn off FEOL,BEOL.

```
$ ruby -e 'FEOL="false"; if FEOL; puts "doing FEOL..."; end'
doing FEOL...
```
Suggestion:
```
# Coerce any flag-args to booleans, case-insensitive, survives absence (nil-class).
FEOL               =     $feol.to_s.downcase=="true"
BEOL               =     $beol.to_s.downcase=="true"
CONNECTIVITY_RULES = $conn_drc.to_s.downcase=="true"
OFFGRID            =  $offgrid.to_s.downcase=="true"
```
## Specifications
github.com//efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr.git : rules/klayout/drc/{gf180mcu.drc,run_drc.py}
8cbf289 2022-12-01T00:12:24-08:00 (HEAD -> main, origin/main, origin/HEAD) Update run_drc_parallel.py

**Comment by atorkmabrains** [comment]
@sto6 We don't allow the usage of the rule deck directly. Please use the ```run_drc.py``` only.

**Comment by sto6** [comment]
If .drc has FEOL="false", calling it thru run_drc.py doesn't help. I agree (prefer) with existing structure to use run_drc.py; but there are folks who insist to by-pass it.

But better still, no reason not to use ruby's OptionParser (so one .drc file does it all: with normal/nice/high-level cmd-line processing), and eliminate obtuse calling like: klayout ... -rd x=y -rd g=h ...
