### ISSUE TITLE
Connectivity DRC issue

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#16]
## Issue
should we run DRC on all user projects with connectivity? It takes 49 hours to run.

related to #15

## Specifications

- Version: `klayout 0.28` commit `b3968c31e5b06325e071b4a79ff9f35979e07bda`
- Platform: `Debian`

**Comment by atorkmabrains** [comment]
@marwaneltoukhy One issue is good enough. I'll close this as it's not important. It's recommended to run the projects using connectivity rules once the project is complete. Only once at the end.
