### ISSUE TITLE
V4.4a tagging all via4 in the design

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#18]
## Expected Behavior
DRC clean

## Actual Behavior
V4.4a tagging all via4 in the design as violations. This behavior is new. See screenshot below

![290](https://user-images.githubusercontent.com/67271180/205925459-21524984-5930-4ad8-a401-5f364d875250.png)

## Steps to Reproduce the Problem

1. `python3 run_drc.py --thr=4 --variant=C --path=/home/marwan/caravel-gf180mcu/gds/caravel_core.gds --run_dir=/home/marwan/caravel-gf180mcu/signoff/caravel_core/standalone_pvr`

## Specifications

- Version: `KLayout 0.27.12`
- Platform: `Debian`

**Comment by marwaneltoukhy** [comment]
Previously it was passing with commit `26564151cb307aeb3c2a6aab56dc742041c3a598`

**Comment by atorkmabrains** [comment]
@marwaneltoukhy Fixed

https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/commit/1dbdca4000023f9f29a275a0c41e9bd86a774896
