### ISSUE TITLE
LVS not working as expected for a basic 2 transistor inverter

### ISSUE THREAD

**Issue by z-a-p-k-i-n-g** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#20]
## Expected Behavior
LVS should give out result that the extracted netlist and the reference netlist match.

## Actual Behavior
It is throwing output as the netlists don't match

## Steps to Reproduce the Problem

1. Run the command 'python run_lvs.py --design=<path-to-.gds file -in-double-quotes> --net=<path-to-.spice-file> --gf180mcu=C

## Specifications

- Version:klayout 0.28
- Platform:Linux
[gf180mcuC_designs.zip](https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/files/10490602/gf180mcuC_designs.zip)

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Could you please test?

**Comment by FaragElsayed2** [comment]
@z-a-p-k-i-n-g 

"M" element is the default for Klayout MOS devices. 

You just need to replace XM? with M? and everything will be okay.

For example: 
`M1 OUT IN VDD VDD pfet_03v3 L=0.28u W=0.44u nf=1 `

Don't forget to pass your substrate name as an input for run_lvs script.

Something like this: 
`python run_lvs.py --design=<path-to-.gds file -in-double-quotes> --net=<path-to-.spice-file>  --gf180mcu=C --lvs_sub="GND"`

**Comment by atorkmabrains** [comment]
@z-a-p-k-i-n-g About exporting netlist for LVS from xschem, I would advise that you ask in xschem channel on slack.

**Comment by z-a-p-k-i-n-g** [comment]
@FaragElsayed2 @atorkmabrains Thanks a lot guys it's working now.
