### ISSUE TITLE
Still some question about the DRC testsuite

### ISSUE THREAD

**Issue by klayoutmatthias** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#3]
Dear all,

when I run the DRC regression tests with 

```
cd rules/klayout/drc/testing
make test-DRC-main
```

I see some failing tests (KLayout version is 0.27.12, same result with 0.28):

```
26-Nov-2022 19:45:04 | INFO    | ## Only failed
       Rule_Name Status
96     PL.1_3.3V   Fail
97       PL.1_5V   Fail
119       NP.3bi   Fail
121       NP.3ci   Fail
130      NP.5cii   Fail
145      PP.3bii   Fail
147      PP.3cii   Fail
156       PP.5di   Fail
169         SB.4   Fail
208        CO.6b   Fail
236        V1.2b   Fail
245        V2.2b   Fail
254        V3.2b   Fail
263        V4.2b   Fail
272        V5.2b   Fail
281        MT.2b   Fail
285        MT.2b   Fail
392       EF.04b   Fail
456      MDP.3ai   Fail
460       MDP.3d   Fail
474      MDP.9ei   Fail
478      MDP.10a   Fail
480      MDP.10a   Fail
489      MDP.17a   Fail
496  Y.PL.1_3.3V   Fail
```

I could not correlate that with DRC_Known_issues.csv - does that mean there is a KLayout bug, or are those known fails?

Thanks,

Matthias

**Comment by atorkmabrains** [comment]
@klayoutmatthias These are known issues and we have all of them in an internal tracking sheet. Please check https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/rules/klayout/drc/testing/DRC_Known_issues.csv

BTW, some of those are kind of related to how Klayout do rounding. It would be nice if you could fix that in klayout. Check the CSV file and lets discuss.

**Comment by klayoutmatthias** [comment]
@atorkmabrains 

Thanks ... but problem is I cannot correlate the above list with the tracking sheet. They seem to be new issues or some not in the sheet. Like I see MDP.17a failing - in the tracking sheet I only see MDP.17c.

Regarding the implementation issue ("how KLayout does rounding"): I'll be happy to help. But maybe you can given a brief example of such a problem? Specifically, what function you use, what is the intended and what the actual output. 

Best regards,

Matthias

**Comment by atorkmabrains** [comment]
@klayoutmatthias Check the file: DRC_Known_issues.csv, you will see issue "Tolerance". All those rules has tolerance issue. You could run the regression to see those.

**Comment by klayoutmatthias** [comment]
@atorkmabrains  I checked NP.1 as one of the Tolerance problems. This is one false positive (width < 0.4):

![image](https://user-images.githubusercontent.com/25720841/204657847-d104e1e6-e131-471f-9ae9-5787711618ab.png)

The markers are kind of strange as only there are two at the corners, but basically it's OK to flag this width as formally it is less than 0.4.

So what is the expectation?

Matthias

**Comment by atorkmabrains** [comment]
@klayoutmatthias
I'm working on updating the regression to make it more relevant.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 This needs to be resolved.

**Comment by atorkmabrains** [comment]
@klayoutmatthias We are moving DRC and LVS to another repo: https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv
