### ISSUE TITLE
missing case for 11K metaltop rule

### ISSUE THREAD

**Issue by proppy** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#30]
It seems that the current metaltop rule misses a case for the 11K variant of the top level metal layer (introduced in https://github.com/RTimothyEdwards/open_pdks/issues/342):
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr/blob/main/rules/klayout/drc/rule_decks/metaltop.drc#L52-L53

@atorkmabrains  can you confirm that those are the same for 9K and 11K as implied by the comment.

/cc @msaligane

**Comment by atorkmabrains** [comment]
@proppy Yes they are according to the DRM:

https://gf180mcu-pdk.readthedocs.io/en/latest/physical_verification/design_manual/drm_07_16.html

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Please make this modification to make sure we include "11K" into account.

**Comment by atorkmabrains** [comment]
Fixed in https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr/pull/116
