### ISSUE TITLE
Clean up the PR and remove DRC and LVS.

### ISSUE THREAD

**Issue by atorkmabrains** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#31]
We moved the DRC and LVS implementation to:
https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv

We will remove them from PR repo.

@mkkassem @RTimothyEdwards @proppy @marwaneltoukhy

**Comment by FaragElsayed2** [comment]
@atorkmabrains This issue has been addressed in [Mabrains](https://github.com/mabrains/globalfoundries-pdk-libs-gf180mcu_fd_pr) repo

**Comment by FaragElsayed2** [comment]
@atorkmabrains Could we close this PR ?

**Comment by atorkmabrains** [comment]
Thanks @FaragElsayed2
