### ISSUE TITLE
LVS tool doesn't recognize the MIM cap 

### ISSUE THREAD

**Issue by StanleyAlwaysLoveYou** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#35]
## Expected Behavior
When I ran the LVS on the layout consists of a resistor and a capacitor, the LVS should indicate that there are a resistor and a capacitor in the layout.

## Actual Behavior
LVS only recognize the resistor but the MIM cap in the layout.
![image](https://user-images.githubusercontent.com/35566294/223808828-9827dcd3-4a21-40dd-b95c-57c1dbc3ecad.png)

## Specifications

- Version: [v0.0-1450-g140b622](https://github.com/proppy/conda-eda/releases/tag/v0.0-1450-g140b622)
- Platform: Klayout, LVS

**Comment by FaragElsayed2** [comment]
@StanleyAlwaysLoveYou Could you please upload your testcase ?

and what is the run command you have used ?

Please use this [PV](https://github.com/efabless/globalfoundries-pdk-libs-gf180mcu_fd_pv) repo for DRC/LVS

**Comment by atorkmabrains** [comment]
@StanleyAlwaysLoveYou I'll close this issue as it has been addressed. Please let me know if you need more help.
