### ISSUE TITLE
Monte Carlo mismatch parameters are faulty

### ISSUE THREAD

**Issue by ChrisZonghaoLi** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#40]
## Expected Behavior

In MC simulations, both threshold voltage `Vth` and other parameters such as charge mobility `mu`, `Cox`, `W`, and `L` (lumped into variable `k`, this is my guess; I am still not too sure what this `k` explicitly accounts for here), should all be varied randomly when the mismatch is considered (`sw_stat_mismatch=1`).

## Actual Behavior

Currently, only the `Vth` mismatches are considered, mismatches on `k` are missing.

## Steps to Reproduce the Problem

If one goes to view the `sm141064.ngspice` file, the variable `mis_k` which should be governing the mismatch of `k`, is not used anywhere in the code.

**Comment by ChrisZonghaoLi** [comment]
@atorkmabrains

**Comment by ChrisZonghaoLi** [comment]
Hi @atorkmabrains do we have any updates on this? Thanks.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 I think we need to take a look at this. Let's plan on discussing this.

**Comment by atorkmabrains** [comment]
@ChrisZonghaoLi Fixed in the last update.

**Comment by ChrisZonghaoLi** [comment]
Hi @atorkmabrains thanks for the updates. So I took a quick look at the new model, and it seems there is this new `mulu0` term added to the mismatch modeling. I could not find this keyword in the BSIM4 manual, what does this `mulu0` mean here? And what is `par_k`? I assume it is some sort of slope parameter but what mismatch does it capture? Thanks.

**Comment by atorkmabrains** [comment]
@ChrisZonghaoLi mulu0 is a BSIM4 instance parameter for low field mobility multiplier. Search for it inside NGSpice documentation and bsim4 model documentation.

**Comment by ChrisZonghaoLi** [comment]
@atorkmabrains nvm I found it (dont know why my Foxit PDF reader can't find it by ctrl+f but I manually find it out on page 162 on the ngspice-40 manual).
