### ISSUE TITLE
DF.13/DF.14 unexpected behavior

### ISSUE THREAD

**Issue by stafverhaegen-chipflow** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#6]
## Expected Behavior

DRC flagging pcomp/ncomp too far away from ntap/ptap resp.

## Actual Behavior

DF.13/DF.14 giving errors for ntap/ptap too far away from a pcomp/ncomp respectively

## Steps to Reproduce the Problem

See project: https://platform.efabless.com/projects/1578
![ntap_too_far_from_pcomp](https://user-images.githubusercontent.com/119108112/204819904-8ce4a58a-f198-48d6-97ff-9cb34b279210.png)

What you see here is a ntap that was flagged that is further than 15um away from a pcomp in the same NWELL.
(Would be nice if klayout on Galaxy would have the technology for gf180mcu so one would get layer names).
 
AFAICS, current DF.13/DF.14 implementation in klayout precheck deck also has other unexpected behavior. It will not mark NWELL with pcomp but without ntap as a DRC error.

## Specifications

- GF-MPW0 precheck on project

**Comment by stafverhaegen-chipflow** [comment]
FYI, I am using own standard cell library.

**Comment by atorkmabrains** [comment]
@stafverhaegen-chipflow Could you please share the test case and how did you run this command?

Here is the recommended command line for this:
```bash
python run_drc.py --variant=C --path=<path_to_your_gds> --run_dir=<path_to_output_dir> 
```

Please make sure to use the latest version from this repo. It's not advised to use Google's version.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Please take a look.

**Comment by atorkmabrains** [comment]
@stafverhaegen-chipflow This issue has been fixed in the latest version in efabless.
