### ISSUE TITLE
rules/klayout/drc/gf180mcu.drc: for gf180mcuC (5LM), must not connect to via5,metaltop and so on

### ISSUE THREAD

**Issue by sto6** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#8]
## Expected Behavior
Do not corrupt connectivity (leading to false or dropped errors) by using layers that are not part of the fab process.
Do not read/merge/count data from such superfluous layers.
## Actual Behavior
Reads (merges, counts) too many layers from GDS.
Connects to too many layers, for any given option like metal_level="5LM".
## Specifications
git@github.com:efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr.git
8cbf289 2022-12-01T00:12:24-08:00 (HEAD -> main, origin/main, origin/HEAD) Update run_drc_parallel.py

Example, for gf180mcuC, i.e. option metal_level="5LM":
a. It reads data from GDS for layers 82 & 53 (via5, metaltop), plus metaltop:dummy,label,slot.
b. It connects from metal5 to metaltop by via5.

For variant-C, "5LM", those layers are not part of the fab process, and should be discarded/ignored
from the GDS. If the GDS happens to have data on those layers, it must NOT be used (as it is now)
to corrupt connectivity-based checks (the bug), and reading/merging data on those layers from
the GDS wastes CPU and memory. Else if such layers are unavoidably read & connected, they
should be enforced to be empty: flag as errors any data found on them (i.e. if not empty, rest
of the DRCs are not to be trusted).
Excerpts from the rules:
```
...
via4           = polygons(41 , 0 ).merged
metal5         = polygons(81 , 0 ).merged
via5           = polygons(82 , 0 ).merged   # <-- unconditional read from GDS of 82 & 53
metaltop       = polygons(53 , 0 ).merged
...
via5_count                     = via5.count()
poly_count                     = poly_count + via5_count
metaltop_count                 = metaltop.count()
poly_count                     = poly_count + metaltop_count
# ^^^ not enumerated here, but similar wasted statements for metaltop: _dummy,_label,_slot
...
elsif METAL_LEVEL == "5LM"
    top_via       = via4
    topmin1_via   = via3
    top_metal     = metal5
    topmin1_metal = metal4
...
  connect(metal5,  via5)   # <-- unconditional connects thru 82 to 53.
  connect(via5,    metaltop)
```

**Comment by atorkmabrains** [comment]
@sto6 I'm not sure I understand the issue. Could we please meet to discuss this?

**Comment by atorkmabrains** [comment]
@sto6 Same as the other issue #11. This is fixed now.
