### ISSUE TITLE
DRC Logs and report redirection

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/globalfoundries-pdk-libs-gf180mcu_fd_pr#9]
## Expected Behavior
Have the option to redirect the reports and logs coming out of the DRC run

## Actual Behavior
It is set by the `run_drc.py` script and can't be changed

**Comment by atorkmabrains** [comment]
@marwaneltoukhy This has been fixed in the new release of the ```run_drc.py``. Please find below the example command:
```bash
python run_drc.py --variant=C --path=./testing/testcases/0.0.DM000013_13_1P6M_9kA_MIMB_WEDGE.gds.gz --run_dir=./drc_runs
```

**Comment by marwaneltoukhy** [comment]
Why is it not reporting if the design is clean or not anymore?

**Comment by atorkmabrains** [comment]
@marwaneltoukhy I'll make that update.

**Comment by atorkmabrains** [comment]
@marwaneltoukhy Please check it again now.

**Comment by marwaneltoukhy** [comment]
Thank you @atorkmabrains, sorry for bugging you but I think there was a report that isn't produced anymore, which counted the number of violations, is it possible to get it back?

**Comment by atorkmabrains** [comment]
@marwaneltoukhy I'll address this tomorrow. I have made many changes for today and closed most of the issues.

**Comment by atorkmabrains** [comment]
@FaragElsayed2 Please take a look

**Comment by atorkmabrains** [comment]
@marwaneltoukhy All the requests above has been addressed.
